name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Build
        run: sh scripts/buildprod.sh

      - id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v3

      - name: Build and push image
        run: gcloud builds submit --tag us-central1-docker.pkg.dev/notely-boot-dev-cicd/notely-ar-repo/notely:latest

      - name: Install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Run migrations
        run: sh scripts/migrateup.sh

      - name: Deploy to GCP
        run: |
          gcloud run deploy notely --image us-central1-docker.pkg.dev/notely-boot-dev-cicd/notely-ar-repo/notely:latest \
          --region us-central1 --allow-unauthenticated --project notely-boot-dev-cicd --max-instances=4
